version: '3'

services:
  # The following defines application containers, which depend on the data-only
  # containers defined above to provide their software layers
  # These should be run with `docker-compose run --rm <application-service>`
  base:
    image: rocm/dev-${OS_VARIANT:-ubuntu-22.04}:${ROCM_VERSION:-latest}
    build:
      context: ./dev
      dockerfile: Dockerfile-${OS_VARIANT:-ubuntu-22.04}
      args:
        ROCM_VERSION: ${ROCM_VERSION}
        AMDGPU_VERSION: ${AMDGPU_VERSION}
    devices:
      - /dev/kfd
      - /dev/dri
    tmpfs:
      - /tmp

  hip:
    image: rocm/dev-${OS_VARIANT:-ubuntu-22.04}:${ROCM_VERSION:-latest}-hip
    build:
      context: ./dev
      dockerfile: Dockerfile-${OS_VARIANT:-ubuntu-22.04}-hip
      args:
        OS_VARIANT: ${OS_VARIANT}
        ROCM_VERSION: ${ROCM_VERSION}
    devices:
      - /dev/kfd
      - /dev/dri
    tmpfs:
      - /tmp

  hip-sdk:
    image: rocm/dev-${OS_VARIANT:-ubuntu-22.04}:${ROCM_VERSION:-latest}-hip-sdk
    build:
      context: ./dev
      dockerfile: Dockerfile-${OS_VARIANT:-ubuntu-22.04}-hip-sdk
      args:
        OS_VARIANT: ${OS_VARIANT}
        ROCM_VERSION: ${ROCM_VERSION}
    devices:
      - /dev/kfd
      - /dev/dri
    tmpfs:
      - /tmp

  ml:
    image: rocm/dev-${OS_VARIANT:-ubuntu-22.04}:${ROCM_VERSION:-latest}-ml
    build:
      context: ./dev
      dockerfile: Dockerfile-${OS_VARIANT:-ubuntu-22.04}-ml
      args:
        OS_VARIANT: ${OS_VARIANT}
        ROCM_VERSION: ${ROCM_VERSION}
    devices:
      - /dev/kfd
      - /dev/dri
    tmpfs:
      - /tmp

  ml-sdk:
    image: rocm/dev-${OS_VARIANT:-ubuntu-22.04}:${ROCM_VERSION:-latest}-ml-sdk
    build:
      context: ./dev
      dockerfile: Dockerfile-${OS_VARIANT:-ubuntu-22.04}-ml-sdk
      args:
        OS_VARIANT: ${OS_VARIANT}
        ROCM_VERSION: ${ROCM_VERSION}
    devices:
      - /dev/kfd
      - /dev/dri
    tmpfs:
      - /tmp

  opencl:
    image: rocm/dev-${OS_VARIANT:-ubuntu-22.04}:${ROCM_VERSION:-latest}-opencl
    build:
      context: ./dev
      dockerfile: Dockerfile-${OS_VARIANT:-ubuntu-22.04}-opencl
      args:
        OS_VARIANT: ${OS_VARIANT}
        ROCM_VERSION: ${ROCM_VERSION}
    devices:
      - /dev/kfd
      - /dev/dri
    tmpfs:
      - /tmp

  opencl-sdk:
    image: rocm/dev-${OS_VARIANT:-ubuntu-22.04}:${ROCM_VERSION:-latest}-opencl-sdk
    build:
      context: ./dev
      dockerfile: Dockerfile-${OS_VARIANT:-ubuntu-22.04}-opencl-sdk
      args:
        OS_VARIANT: ${OS_VARIANT}
        ROCM_VERSION: ${ROCM_VERSION}
    devices:
      - /dev/kfd
      - /dev/dri
    tmpfs:
      - /tmp

  openmp-sdk:
    image: rocm/dev-${OS_VARIANT:-ubuntu-22.04}:${ROCM_VERSION:-latest}-openmp-sdk
    build:
      context: ./dev
      dockerfile: Dockerfile-${OS_VARIANT:-ubuntu-22.04}-openmp-sdk
      args:
        OS_VARIANT: ${OS_VARIANT}
        ROCM_VERSION: ${ROCM_VERSION}
    devices:
      - /dev/kfd
      - /dev/dri
    tmpfs:
      - /tmp

  complete:
    image: rocm/dev-${OS_VARIANT:-ubuntu-22.04}:${ROCM_VERSION:-latest}-complete
    build:
      context: ./dev
      dockerfile: Dockerfile-${OS_VARIANT:-ubuntu-22.04}-complete
      args:
        OS_VARIANT: ${OS_VARIANT}
        ROCM_VERSION: ${ROCM_VERSION}
    devices:
      - /dev/kfd
      - /dev/dri
    tmpfs:
      - /tmp

  complete-sdk:
    image: rocm/dev-${OS_VARIANT:-ubuntu-22.04}:${ROCM_VERSION:-latest}-complete-sdk
    build:
      context: ./dev
      dockerfile: Dockerfile-${OS_VARIANT:-ubuntu-22.04}-complete-sdk
      args:
        OS_VARIANT: ${OS_VARIANT}
        ROCM_VERSION: ${ROCM_VERSION}
    devices:
      - /dev/kfd
      - /dev/dri
    tmpfs:
      - /tmp

  term:
    image: rocm/rocm-terminal:${ROCM_VERSION:-latest}
    build:
      context: ./rocm-terminal
      dockerfile: Dockerfile-${OS_VARIANT:-ubuntu-22.04}
      args:
        ROCM_VERSION: ${ROCM_VERSION}
        TERM_FLAVOR: ${TERM_FLAVOR:-complete-sdk}
        UID: ${UID}
        RENDER_GID: ${RENDER_GID}
    devices:
      - /dev/kfd
      - /dev/dri
#   tmpfs:
#     - /tmp
    volumes:
      - ~/venv:/home/rocm-user/venv
      - /home/src:/home/rocm-user/src
      - /tmp:/tmp

  xterm:
    image: rocm/rocm-terminal:${ROCM_VERSION:-latest}-x11
    build:
      context: ./rocm-terminal
      dockerfile: Dockerfile-${OS_VARIANT:-ubuntu-22.04}-x11
      args:
        ROCM_VERSION: ${ROCM_VERSION}
        TERM_FLAVOR: ${XTERM_FLAVOR:-complete}
        UID: ${UID}
        RENDER_GID: ${RENDER_GID}
    environment:
      - DISPLAY
      - PULSE_SERVER=unix:/tmp/pulse/native
      - PULSE_COOKIE=/tmp/pulse/cookie
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/kfd
      - /dev/dri
      - /dev/fuse
    tmpfs:
      - /tmp
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/${UID:-1000}/pulse/native:/tmp/pulse/native
      - ~/.config/pulse/cookie:/tmp/pulse/cookie:ro
      - ~/venv:/home/rocm-user/venv
      - ~/src:/home/rocm-user/src
