version: '3'

services:
  # The following defines application containers, which depend on the data-only
  # containers defined above to provide their software layers
  # These should be run with `docker-compose run --rm <application-service>`
  dev:
    image: rocm/dev-${OS_VARIANT}:${ROCM_VERSION}
    build:
      context: ./dev
      dockerfile: Dockerfile-${OS_VARIANT}
      args:
        ROCM_VERSION: ${ROCM_VERSION}
        AMDGPU_VERSION: ${AMDGPU_VERSION}
        RENDER_GID: ${RENDER_GID}
    devices:
      - /dev/kfd
      - /dev/dri
    tmpfs:
      - /tmp

  dev-complete:
    image: rocm/dev-${OS_VARIANT}:${ROCM_VERSION}-complete
    build:
      context: ./dev
      dockerfile: Dockerfile-${OS_VARIANT}-complete
      args:
        ROCM_VERSION: ${ROCM_VERSION}
    devices:
      - /dev/kfd
      - /dev/dri
    tmpfs:
      - /tmp

  rocm:
    image: rocm/rocm-terminal:${ROCM_VERSION}-${OS_VARIANT}${TERM_IMAGE_VARIANT}
    build:
      context: ./rocm-terminal
      dockerfile: Dockerfile-${OS_VARIANT}
      args:
        ROCM_VERSION: ${ROCM_VERSION}
        TERM_IMAGE_VARIANT: ${TERM_IMAGE_VARIANT}
        RENDER_GID: ${RENDER_GID}
    devices:
      - /dev/kfd
      - /dev/dri
    tmpfs:
      - /tmp
    volumes:
      - ~:/usr/local/src/host-home
