# This dockerfile is meant to serve as a rocm base image.
# Add rocm-lib package to rocm/dev-ubuntu-20.04 image

ARG OS_VARIANT=ubuntu-20.04
ARG ROCM_VERSION=5.2.3

FROM rocm/dev-${OS_VARIANT}:${ROCM_VERSION}-hip-sdk

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  vulkan-amdgpu \
  vulkan-tools \
  rocm-opencl-sdk \
  clinfo \
  rocm-openmp-sdk \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
