# This dockerfile is meant to serve as a rocm base image.
# Add rocm-lib package to rocm/dev-ubuntu-20.04 image

ARG OS_VARIANT=ubuntu-20.04
ARG ROCM_VERSION=5.3

FROM rocm/dev-${OS_VARIANT}:${ROCM_VERSION}-opencl-ml

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  rocm-opencl-sdk \
  miopen-opencl-dev \
  python3-dev \
  libnuma-dev \
  build-essential \
  && apt-mark auto rocm-opencl-runtime miopen-opencl libnuma1 \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
