FROM amd64/almalinux:8
LABEL maintainer=dl.mlsedevops@amd.com

ARG ROCM_VERSION=6.1
ARG AMDGPU_VERSION=6.1

# Base
RUN yum -y install git java-1.8.0-openjdk python; yum clean all

# Enable epel-release repositories
RUN dnf install -y 'dnf-command(config-manager)'
RUN dnf config-manager --set-enabled powertools
RUN dnf install -y epel-release

# Install required base build and packaging commands for ROCm
RUN yum -y install \
    ca-certificates \
    bc \
    bridge-utils \
    cmake \
    cmake3 \
    dkms \
    doxygen \
    dpkg \
    dpkg-dev \
    dpkg-perl \
    elfutils-libelf-devel \
    expect \
    file \
    python3-pip \
    gettext \
    gcc-c++ \
    libgcc \
    lzma \
    glibc.i686 \
    ncurses \
    ncurses-base \
    ncurses-libs \
    numactl-devel \
    numactl-libs \
    libssh \
    libunwind-devel \
    libunwind \
    llvm \
    llvm-libs \
    make \
    openssl \
    openssl-libs \
    openssh \
    openssh-clients \
    pciutils \
    pciutils-devel \
    pciutils-libs \
    perl \
    pkgconfig \
    qemu-kvm \
    re2c \
    kmod \
    rpm \
    rpm-build \
    subversion \
    wget

# Enable the epel repository for fakeroot
RUN yum install -y fakeroot
RUN yum clean all

# Install ROCm repo paths
RUN echo -e "[ROCm]\nname=ROCm\nbaseurl=https://repo.radeon.com/rocm/rhel8/$ROCM_VERSION/main\nenabled=1\ngpgcheck=0" >> /etc/yum.repos.d/rocm.repo
RUN echo -e "[amdgpu]\nname=amdgpu\nbaseurl=https://repo.radeon.com/amdgpu/$AMDGPU_VERSION/rhel/8.9/main/x86_64\nenabled=1\ngpgcheck=0" >> /etc/yum.repos.d/amdgpu.repo

# Install ROCm
COPY scripts/install_versioned_rocm.sh install_versioned_rocm.sh
RUN bash install_versioned_rocm.sh ${ROCM_VERSION}
RUN rm install_versioned_rocm.sh
