# This dockerfile is meant to serve as a rocm base image.
# Add rocm-lib package to rocm/dev-ubuntu-20.04 image

ARG ROCM_VERSION=5.2.3

FROM rocm/dev-ubuntu-20.04:$ROCM_VERSION

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  rocm-libs \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
