# This dockerfile is meant to serve as a rocm base image.
# Add rocm-lib package to rocm/dev-ubuntu-20.04 image

ARG OS_VARIANT=ubuntu-20.04
ARG ROCM_VERSION=6.1

FROM rocm/dev-${OS_VARIANT}:${ROCM_VERSION}-hip

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  rocm-hip-sdk \
  python3-dev \
  build-essential \
  && apt-mark auto rocm-hip-libraries \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
