FROM quay.io/pypa/manylinux2014_x86_64
LABEL maintainer=dl.mlsedevops@amd.com

#NOTE: manylinux image already has devtoolset installed

ARG ROCM_VERSION=6.4.1
ARG AMDGPU_VERSION=6.4.1

# Install the ROCm rpms
RUN yum clean all
RUN echo -e "[ROCm]\nname=ROCm\nbaseurl=https://repo.radeon.com/rocm/yum/$ROCM_VERSION/main\nenabled=1\ngpgcheck=0" >> /etc/yum.repos.d/rocm.repo
RUN echo -e "[amdgpu]\nname=amdgpu\nbaseurl=https://repo.radeon.com/amdgpu/$AMDGPU_VERSION/rhel/7/main/x86_64\nenabled=1\ngpgcheck=0" >> /etc/yum.repos.d/amdgpu.repo

RUN yum install -y rocm-dev
