# This dockerfile is meant to be personalized, and serves as a template and demonstration.
# Modify it directly, but it is recommended to copy this dockerfile into a new build context (directory),
# modify to taste and modify docker-compose.yml.template to build and run it.

# It is recommended to control docker containers through 'docker-compose' https://docs.docker.com/compose/
# Docker compose depends on a .yml file to control container sets
# rocm-setup.sh can generate a useful docker-compose .yml file
# `docker-compose run --rm <rocm-terminal>`

# If it is desired to run the container manually through the docker command-line, the following is an example
# 'docker run -it --rm -v [host/directory]:[container/directory]:ro <user-name>/<project-name>'.

ARG ROCM_VERSION=6.1
ARG TERM_FLAVOR
ARG USER_NAME=rocm-user

FROM rocm/dev-ubuntu-20.04:${ROCM_VERSION}${TERM_FLAVOR}

ARG UID
ARG RENDER_GID

# Initialize the image
# Modify to pre-install dev tools and ROCm packages
RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  git \
  vim-nox \
  less \
  cmake-curses-gui \
  python3-pip \
  python3-venv \
  rocm-developer-tools
RUN apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Grant members of 'sudo' group passwordless privileges
# Comment out to require sudo
COPY sudo-nopasswd /etc/sudoers.d/sudo-nopasswd

# This is meant to be used as an interactive developer container
# Create user $USER_NAME as member of sudo group
# Append /opt/rocm/bin to the system PATH variable
RUN UID_ADD=; [ -z "$UID" ] || UID_ADD="-u $UID"; \
    if [ -z "$RENDER_GID" ]; then \
      useradd --create-home $UID_ADD -G sudo,video --shell /bin/bash $USER_NAME; \
    else \
      groupadd -g $RENDER_GID render; \
      useradd --create-home $UID_ADD -G sudo,video,render --shell /bin/bash $USER_NAME; \
    fi
USER $USER_NAME
WORKDIR /home/$USER_NAME
ENV PATH "${PATH}:/opt/rocm/bin"

# The following are optional enhancements for the command-line experience
# Uncomment the following to install a pre-configured vim environment based on http://vim.spf13.com/
# 1.  Sets up an enhanced command line dev environment within VIM
# 2.  Aliases GDB to enable TUI mode by default
#RUN curl -sL https://j.mp/spf13-vim3 | bash && \
#    echo "alias gdb='gdb --tui'\n" >> ~/.bashrc

# Default to a login shell
CMD ["bash", "-l"]
